### ISSUE TITLE
Scenario Report not created When large data table is used

### ISSUE THREAD

**Issue by ndrsfrr** [hubidu/bifrost-io#2]
**When I have a test with a large data table**
**And I have a test without a data table**

> Feature('Test with data set', {retries: 0});
>
>let parameter = new DataTable(['jobSituation',                    'occupation',                                 'education',             >'age', 'fractionOfficeWork', 'staffResponsibility', 'industry',         'familyStatus',         'smoker', 'benefit', >'benefitAgeLimit', 'resultCounter', 'expensivePrice', 'cheapestPrice', 'mostExpensiveTariff',       >'cheapestTariff']);
>parameter.add([                'Angestellter oder Selbständiger', 'Industriekaufmann,frau',                     >'Berufsausbildung',      '26',  '100',                '0',                   'Stahl',            'Keine Angabe',         'nein',   >'1500',    '65',              '49',            '132,51',         '40,94',         'WWK - BioRisk Komfort',     'Nürnberger - >SBU2901 Comfort']);

>Data(parameter).Scenario('When the test has a lot of data parameters Then a report is not created', function(I, current) {
>  I.amOnPage('onboarding');
>  I.see('something that is not there');
>});
>
>Scenario('When the test has no data or a small data table Then a report is created', function(I) {
> I.amOnPage('onboarding');
> I.see('something that is not there');
>});

**Then a report is just created for the test without a data table**

![image](https://user-images.githubusercontent.com/39731774/40662081-a2df83b6-6355-11e8-98c5-7708d88b6232.png)

I see two errors:
local:
>ERROR in _test hook RangeError: Maximum call stack size exceeded
>    at normalizeStringWin32 (path.js:33:30)
>    at Object.resolve (path.js:338:20)
>    at sync (C:\git\ui-tests\node_modules\mkdirp\index.js:68:14)

Bamboo:
ERROR in _test hook { Error: ENAMETOOLONG: name too long, mkdir '/opt/app/__out/Calculation -- When I enter my data Then I see a result calculation  jobSituationAngestellter oder Selbstndiger,occupationUnternehmensberater,in,educationPromotion,age29,fractionOfficeWork100,staffResponsibility15,industryGesundheitswesen,familyStatusPaar mit Kind(ern),smokerja,benefit5000,benefitAgeLimit65,resultCounter44,expensivePrice273,21,cheapestPrice105,50,mostExpensiveTariffuniVersa - SBU,cheapestTariffInterRisk - S-M.A.R.T/1527553264387'
at Object.fs.mkdirSync (fs.js:902:18)
at Function.sync (/opt/app/node_modules/mkdirp/index.js:71:13)
at new DashboardTestContext (/opt/app/node_modules/bifrost-io/dashboard-test-context.js:189:16)
at DashboardClient.createTestContext (/opt/app/node_modules/bifrost-io/index.js:20:21)
at BifrostIOHelper._test (/opt/app/node_modules/bifrost-io/codeceptjs/dashboard_helper.js:66:33)
at Object.keys.forEach (/opt/app/node_modules/codeceptjs/lib/listener/helpers.js:14:25)
at Array.forEach (<anonymous>)
at runHelpersHook (/opt/app/node_modules/codeceptjs/lib/listener/helpers.js:13:26)
at EventEmitter.event.dispatcher.on (/opt/app/node_modules/codeceptjs/lib/listener/helpers.js:34:5)
at EventEmitter.emit (events.js:185:15)
at EventEmitter.emit (domain.js:422:20)
at Object.emit (/opt/app/node_modules/codeceptjs/lib/event.js:49:28)
at Context.test.fn (/opt/app/node_modules/codeceptjs/lib/scenario.js:98:13)
at callFnAsync (/opt/app/node_modules/mocha/lib/runnable.js:377:21)
at Test.Runnable.run (/opt/app/node_modules/mocha/lib/runnable.js:324:7)
at Runner.runTest (/opt/app/node_modules/mocha/lib/runner.js:442:10)
at /opt/app/node_modules/mocha/lib/runner.js:560:12
at next (/opt/app/node_modules/mocha/lib/runner.js:356:14)
at /opt/app/node_modules/mocha/lib/runner.js:366:7
at next (/opt/app/node_modules/mocha/lib/runner.js:290:14)
at /opt/app/node_modules/mocha/lib/runner.js:329:7
at done (/opt/app/node_modules/mocha/lib/runnable.js:301:5)
errno: -36,
code: 'ENAMETOOLONG',
syscall: 'mkdir',
path: '/opt/app/__out/Calculation -- When I enter my data Then I see a result calculation  jobSituationAngestellter oder Selbstndiger,occupationUnternehmensberater,in,educationPromotion,age29,fractionOfficeWork100,staffResponsibility15,industryGesundheitswesen,familyStatusPaar mit Kind(ern),smokerja,benefit5000,benefitAgeLimit65,resultCounter44,expensivePrice273,21,cheapestPrice105,50,mostExpensiveTariffuniVersa - SBU,cheapestTariffInterRisk - S-M.A.R.T/1527553264387' }

**Comment by hubidu** [comment]
Codeceptjs fails to produce an error screenshot in the case with the data table containing lots of attributes since it generates a filename which is ultimately too long for the operating system to handle.

However I will do my best to handle this situation gracefully in bifrost-io.

**Comment by hubidu** [comment]
FYI There is already a codeceptjs issue (https://github.com/Codeception/CodeceptJS/issues/1106) for that
