### ISSUE TITLE
Highlight an element throws a warning

### ISSUE THREAD

**Issue by ndrsfrr** [hubidu/bifrost-io#8]
**WHEN I execute tests with following selectors
THEN I get a warning in the console and logs**

**Example selectors:**
//a[text()="Nutzungsbedingungen"]
//a[@class="PersonalDataPageAgreementSection-link"][text()="Vorab-Informationen"]
input[testid="from"]

**Drivers**
WebdriverIO
Puppeteer

**Warning:**
WARNING Failed to highlight element [object Object] Error: Evaluation failed: DOMException: Failed to execute 'querySelectorAll' on 'Document': '[object Object]' is not a valid selector.
    at querySel (__puppeteer_evaluation_script__:24:29)
    at __puppeteer_evaluation_script__:34:17
    at ExecutionContext.evaluateHandle (C:\git\ui-tests-desktopapp\node_modules\puppeteer\lib\ExecutionContext.js:106:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\git\ui-tests-desktopapp\node_modules\puppeteer\lib\helper.js:144:27)
    at ExecutionContext.evaluate (C:\git\ui-tests-desktopapp\node_modules\puppeteer\lib\ExecutionContext.js:58:31)
    at ExecutionContext.<anonymous> (C:\git\ui-tests-desktopapp\node_modules\puppeteer\lib\helper.js:145:23)
    at Frame.evaluate (C:\git\ui-tests-desktopapp\node_modules\puppeteer\lib\FrameManager.js:439:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\git\ui-tests-desktopapp\node_modules\puppeteer\lib\helper.js:144:27)
    at Page.evaluate (C:\git\ui-tests-desktopapp\node_modules\puppeteer\lib\Page.js:728:43)
    at Page.<anonymous> (C:\git\ui-tests-desktopapp\node_modules\puppeteer\lib\helper.js:145:23)
    at Puppeteer.executeScript (C:\git\ui-tests-desktopapp\node_modules\codeceptjs\lib\helper\Puppeteer.js:1163:29)
    at BifrostIOHelper._beforeStep (C:\git\ui-tests-desktopapp\node_modules\bifrost-io\codeceptjs\dashboard_helper.js:234:26)
    at recorder.add (C:\git\ui-tests-desktopapp\node_modules\codeceptjs\lib\listener\helpers.js:21:69)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by hubidu** [comment]
Working on it
